### ISSUE TITLE
Attribute error 

### ISSUE THREAD

**Issue by GergelyM** [coetaur0/staticfg#1]
Installed the package successfully on two Linux box Raspbian 8 Jessie (Python 3.4) and Ubuntu 18.04 (Python 3.6) following the instructions in the Readme.
But both throw the same error:

Ubuntu 18.04 / Python 3.6
```
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from staticfg import CFGBuilder
>>> cfg = CFGBuilder().build_from_file('the_script.py', './the_script.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 124, in build_from_file
    return self.build_from_src(name, src)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 108, in build_from_src
    return self.build(name, tree)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 374, in visit_FunctionDef
    self.new_functionCFG(node, async=False)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 201, in new_functionCFG
    self.current_id)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 241, in visit_Expr
    self.generic_visit(node)
  File "/usr/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 246, in visit_Call
    func_name = "{}.{}".format(func.value.id, func.attr)
AttributeError: 'Attribute' object has no attribute 'id'
```
Raspbian 8 / Python 3.4
```
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from staticfg import CFGBuilder
>>> cfg = CFGBuilder().build_from_file('the_script.py', './the_script.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/staticfg/builder.py", line 124, in build_from_file
    return self.build_from_src(name, src)
  File "/usr/local/lib/python3.4/dist-packages/staticfg/builder.py", line 108, in build_from_src
    return self.build(name, tree)
  File "/usr/local/lib/python3.4/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/local/lib/python3.4/dist-packages/staticfg/builder.py", line 374, in visit_FunctionDef
    self.new_functionCFG(node, async=False)
  File "/usr/local/lib/python3.4/dist-packages/staticfg/builder.py", line 201, in new_functionCFG
    self.current_id)
  File "/usr/local/lib/python3.4/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/local/lib/python3.4/dist-packages/staticfg/builder.py", line 241, in visit_Expr
    self.generic_visit(node)
  File "/usr/lib/python3.4/ast.py", line 255, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/local/lib/python3.4/dist-packages/staticfg/builder.py", line 246, in visit_Call
    func_name = "{}.{}".format(func.value.id, func.attr)
AttributeError: 'Attribute' object has no attribute 'id'
```

The target script requires Python 2.7 to run if that's relevant to this issue.

**Comment by coetaur0** [comment]
In its current state the package does not yet support the entire Python language, which is why some errors can still show up when building CFGs, especially when working with objects and classes. 

Without access to the original script for which the CFG was built in your case, it is difficult to say what the problem exactly was. However, reading the error message above, it seems that a method was called through some object's attribute in the code. These chains of attribute calls weren't supported by the implementation, but I have updated the package to correct this. 
If you reinstall the updated package and try again to build the CFG for your script, this should hopefully solve your issue.

**Comment by GergelyM** [comment]
Thanks for the answer. My aim was to give an informative and hopefully
helpful feedback.

**Comment by coetaur0** [comment]
Of course. Thanks for the feedback and for finding this error! Did the modifications solve your problem?

**Comment by coetaur0** [comment]
I'm taking the liberty of closing this issue. Don't hesitate to reopen it if the problem persists.

**Comment by GergelyM** [comment]
My apologies for the late reply.

I reinstalled `staticfg` with `pip3 install -I staticfg`
Then I run `staticfg` with three different python code. 
- "A"  with multiple classes 
- "B" is a rest api using function decorators and several functions
- "C" is the client for the second with command line argument parsing and much fewer functions.
All failed similarly but with a slightly different message.

"A"
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 124, in build_from_file
    return self.build_from_src(name, src)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 108, in build_from_src
    return self.build(name, tree)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 374, in visit_FunctionDef
    self.new_functionCFG(node, async=False)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 201, in new_functionCFG
    self.current_id)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 308, in visit_If
    self.visit(child)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 300, in visit_If
    self.visit(child)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 241, in visit_Expr
    self.generic_visit(node)
  File "/usr/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 246, in visit_Call
    func_name = "{}.{}".format(func.value.id, func.attr)
AttributeError: 'Attribute' object has no attribute 'id'
```

"B"
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 124, in build_from_file
    return self.build_from_src(name, src)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 108, in build_from_src
    return self.build(name, tree)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 374, in visit_FunctionDef
    self.new_functionCFG(node, async=False)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 201, in new_functionCFG
    self.current_id)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 253, in visit_Assign
    self.generic_visit(node)
  File "/usr/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 246, in visit_Call
    func_name = "{}.{}".format(func.value.id, func.attr)
AttributeError: 'Str' object has no attribute 'id'
```

"C"
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 124, in build_from_file
    return self.build_from_src(name, src)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 108, in build_from_src
    return self.build(name, tree)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 374, in visit_FunctionDef
    self.new_functionCFG(node, async=False)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 201, in new_functionCFG
    self.current_id)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 253, in visit_Assign
    self.generic_visit(node)
  File "/usr/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/staticfg/builder.py", line 246, in visit_Call
    func_name = "{}.{}".format(func.value.id, func.attr)
AttributeError: 'Call' object has no attribute 'id'
```

**Comment by coetaur0** [comment]
Hi, 
I see that you reinstalled staticfg from PyPI and not from the Github repository. Unfortunately, I hadn't yet uploaded the corrected version to the package index (sorry about that). I have done it now. Please try reinstalling the new version of the package and running your code again. Hopefully, you shouldn't get those errors anymore.
