### ISSUE TITLE
AssertionError: Target of a link must be a block`

### ISSUE THREAD

**Issue by aifight** [coetaur0/staticfg#3]
Hello! Thanks for your excellent code. When I use staticfg, I encountered error below, could you help me to fix it?:
```
Traceback (most recent call last):
  File "debug-more-data-get_pycfg_dot.py", line 49, in <module>
    cfg = CFGBuilder().build_from_file(cfg_name, input_file)
  File "/data/wanyao/work/code/test-extr-com/fix-case-split/staticfg-dj/staticfg/builder.py", line 124, in build_from_file
    return self.build_from_src(name, src)
  File "/data/wanyao/work/code/test-extr-com/fix-case-split/staticfg-dj/staticfg/builder.py", line 108, in build_from_src
    return self.build(name, tree)
  File "/data/wanyao/work/code/test-extr-com/fix-case-split/staticfg-dj/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/share/anaconda3/envs/36t041/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/share/anaconda3/envs/36t041/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/share/anaconda3/envs/36t041/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/data/wanyao/work/code/test-extr-com/fix-case-split/staticfg-dj/staticfg/builder.py", line 386, in visit_FunctionDef
    self.new_functionCFG(node, asynchr=False)
  File "/data/wanyao/work/code/test-extr-com/fix-case-split/staticfg-dj/staticfg/builder.py", line 201, in new_functionCFG
    self.current_id)
  File "/data/wanyao/work/code/test-extr-com/fix-case-split/staticfg-dj/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/share/anaconda3/envs/36t041/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/share/anaconda3/envs/36t041/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/share/anaconda3/envs/36t041/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/data/wanyao/work/code/test-extr-com/fix-case-split/staticfg-dj/staticfg/builder.py", line 284, in visit_Assert
    self.add_exit(self.current_block, failblock, invert(node.test))
  File "/data/wanyao/work/code/test-extr-com/fix-case-split/staticfg-dj/staticfg/builder.py", line 158, in add_exit
    newlink = Link(block, nextblock, exitcase)
  File "/data/wanyao/work/code/test-extr-com/fix-case-split/staticfg-dj/staticfg/model.py", line 119, in __init__
    assert type(target) == Block, "Target of a link must be a block"
AssertionError: Target of a link must be a block
``````

Here are two example files that cause the error
first one:
```python
def load_passphrase_from_file():
	vf_path = os.path.expanduser(kVFPassphraseFile)
	assert (os.access(vf_path, os.F_OK) and os.access(vf_path, os.R_OK)), ('%s	must	exist	and	be	readable' % vf_path)
	with open(vf_path) as f:
		user_data = f.read()
	return user_data.strip('\n')

``````
second:
```python
def test_find_number_6():
	s = 'query1e5	not	found'
	r = find_number(s)
	assert (s[r[0]:r[1]] == '1e5')
``````

**Comment by coetaur0** [comment]
Hi, thanks for using the package! 
The error you had was due to a typo in the visit_Assert() method of the CFGBuilder class. I have corrected it and updated the package on PyPI. If you reinstall the latest version of the package (either directly from this repository's source code or from PyPI), the error should now be gone and everything should work.

**Comment by aifight** [comment]
@coetaur0  Yeah, it works! Thank you! And I was wondering if I can use some trick to make staticfg support python2 ?

**Comment by coetaur0** [comment]
You can try to use the package as is with Python2, but unfortunately I cannot guarantee that it'll work. The package was initially developed for Python3, and there might be parts of the code that would need to be changed for it to work properly with Python2.
