### ISSUE TITLE
Problem with .function() syntax

### ISSUE THREAD

**Issue by JJK96** [coetaur0/staticfg#8]
I'm not entirely sure what is the problem, but I have a couple of examples:

This one fails
```python
a = [1,2].count(2)
print(a)
```

But this one works
```python
print([1,2].count(2))
```

The error I get on the failing one is
```
Traceback (most recent call last):
  File "/home/jjk/git/staticfg/examples/build_cfg.py", line 15, in <module>
    cfg = CFGBuilder().build_from_file(cfg_name, args.input_file)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 124, in build_from_file
    return self.build_from_src(name, src)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 108, in build_from_src
    return self.build(name, tree)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/lib/python3.7/ast.py", line 270, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 268, in visit_Assign
    self.generic_visit(node)
  File "/usr/lib/python3.7/ast.py", line 272, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 263, in visit_Call
    func_name = visit_func(func)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 255, in visit_func
    func_name += "." + node.attr
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by vishwesh-D-kumar** [comment]
Hey 
@coetaur0 
Could adding a default return type in visit_Call() be a possible solution to the same?
this is my proposed change in visit_Call()
```
            else:
                return type(node).__name__
````
This would ensure no code breakage and take care of the above issue and #6 
For all possible absolute data types (Lists,Strs,sets) , this would work .
The output of the same is an additions of List.count() to self.current_block.func_calls

**Comment by TruncatedDinosour** [comment]
Damn, still an issue after 3 years

**Comment by sss1h** [comment]
已收到您的邮件。如果急需回复，请致电15504411531。

**Comment by coetaur0** [comment]
Hi, sorry for the very late reply (better late than never, I guess...). I have applied the changes proposed by @vishwesh-D-kumar, which does indeed solve the issues in #8 and #16. Thanks for the fix !
